import { STORAGE_KEYS } from "./ui/state.js";
import { storageGet } from "./ui/dom.js";
import { setConnectionStatus, loadSnapshot, switchTab } from "./ui/engine-client.js";
import { renderAll } from "./ui/render-shared.js";
import { applyTheme, initializeDesktopWindowControls } from "./ui/desktop.js";
import { applyMinimalMode } from "./ui/minimal.js";
import { bindHeaderLayout } from "./ui/header-layout.js";
import { bindEvents } from "./ui/events.js";

if (window.dashboardDesktop?.getPathForFile) document.documentElement.dataset.desktop = "true";
applyTheme(storageGet(STORAGE_KEYS.theme) || "dark");
applyMinimalMode(storageGet(STORAGE_KEYS.minimalMode) === "true", { persist: false, render: false });
setConnectionStatus("connecting", "正在连接 Dashboard Engine…", "业务数据由 Engine Server 单一持有。");
renderAll();
bindEvents();
bindHeaderLayout();
switchTab(location.hash.slice(1) || storageGet(STORAGE_KEYS.activeTab) || "paths", false);
if (storageGet(STORAGE_KEYS.minimalMode) === "true") switchTab("paths", false);
initializeDesktopWindowControls();
loadSnapshot();
