export const STORAGE_KEYS = {
  paths: "local-dashboard.paths.v1",
  notes: "local-dashboard.notes.v1",
  theme: "local-dashboard.theme.v1",
  alwaysOnTop: "local-dashboard.window-always-on-top.v1",
  activeTab: "local-dashboard.active-tab.v1",
  migration: "local-dashboard.engine-migration.v1",
  silentRefreshAt: "local-dashboard.path-silent-refresh-at.v1",
  minimalMode: "local-dashboard.minimal-mode.v1",
};

export const state = {
  connected: false,
  connecting: true,
  activeTab: "paths",
  aggregateRevision: 0,
  snapshotUpdatedAt: "",
  pathSearch: "",
  pathCategory: "all",
  pathStatus: "any",
  projectSearch: "",
  projectFilter: "all",
  noteSearch: "",
  noteCategory: "all",
  sortMode: "smart",
  activeViewId: "",
  dropQueue: [],
  dropPlan: [],
  pathDialogFromDrop: false,
  highlightPathId: null,
  highlightProjectId: null,
  highlightNoteId: null,
  tags: [],
  paths: [],
  notes: [],
  projects: [],
  savedViews: [],
  probeResults: new Map(),
  launcherAvailable: null,
  launcherRevision: 0,
  launcherDefinitions: new Map(),
  launcherRuns: new Map(),
  legacyChecked: false,
  alwaysOnTop: false,
  minimalMode: false,
};
